# Generated by Django 4.0.2 on 2022-04-03 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название проекта')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Ссылка')),
            ],
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(default=True, null=True, verbose_name='Активна')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todoapp.project', verbose_name='Название проекта')),
            ],
        ),
    ]
