# Generated by Django 4.0.2 on 2022-02-28 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='created_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='updated_date',
            new_name='updated_at',
        ),
    ]
