# Generated by Django 4.0.2 on 2022-02-28 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0001_initial'),
        ('todoapp', '0002_rename_created_date_todo_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usersapp.user'),
        ),
    ]
